name: Build and Publish Docker Image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 1.11
    - name: Build with Maven
      run: mvn clean install
    - uses: mr-smithers-excellent/docker-build-push@v3
      with:
        image: omkarpatel00/op
        registry: docker.pkg.github.com
        githubOrg: override-org # optional
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
